# Generated by Django 3.0.3 on 2020-03-24 15:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wordsgame', '0002_mistake_count'),
    ]

    operations = [
        migrations.CreateModel(
            name='IiWord',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('body', models.CharField(db_index=True, max_length=150)),
                ('correct', models.CharField(db_index=True, max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='NnWord',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('body', models.CharField(db_index=True, max_length=150)),
                ('correct', models.CharField(db_index=True, max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='OvaWord',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('body', models.CharField(db_index=True, max_length=150)),
                ('correct', models.CharField(db_index=True, max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='PreWord',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('body', models.CharField(db_index=True, max_length=150)),
                ('correct', models.CharField(db_index=True, max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='ZnakWord',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('body', models.CharField(db_index=True, max_length=150)),
                ('correct', models.CharField(db_index=True, max_length=10)),
            ],
        ),
    ]
