# Generated by Django 3.0.3 on 2020-03-24 16:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wordsgame', '0003_iiword_nnword_ovaword_preword_znakword'),
    ]

    operations = [
        migrations.DeleteModel(
            name='NnWord',
        ),
    ]
