# Generated by Django 3.0.3 on 2020-03-26 13:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wordsgame', '0005_chikword'),
    ]

    operations = [
        migrations.CreateModel(
            name='OyoWord',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('body', models.CharField(db_index=True, max_length=150)),
                ('correct', models.CharField(db_index=True, max_length=10)),
            ],
        ),
    ]
